### ISSUE TITLE
For some reason, after a pull, the digest of the empty key is not a commit, but pointing to a tree object

### ISSUE THREAD

**Issue by hannesm** [robur-coop/git-kv#6]
So, I expected to retrieve the commit ID consulting "digest kv (Mirage_kv.Key.empty)", but I get a tree.

I couldn't find the c1a3bd2e92e5f35c172fc2563833e22e7ddde68d in opam-repository, but expected 9f26a2181d2f46e23b62061679bdddb92684f204.

What is the suggested path to retrieve the commit where the git_kv is at?

**Comment by dinosaure** [comment]
> What is the suggested path to retrieve the commit where the git_kv is at?

It is normal for you to have the hash of the tree with `digest`. The semantics of `digest` consist of obtaining the hash of a path (a `Mirage_kv.key`), which only involves tree or blob objects (but not commits, which are another type of object referring to a history - not a path).

We can imagine a new function (like `Git_kv.commit`) which can expose the current commit in the same way as `Git_kv.branch` exposes the current branch.

**Comment by hannesm** [comment]
fixed by a PR, introducing that value `commit`.
